<a href="https://colab.research.google.com/github/financieras/retos_python/blob/main/Conecta_cuatro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Crear el tablero
board = np.zeros((6, 7))

# Función para colocar una ficha en el tablero
def drop_piece(board, row, col, piece):
    board[row][col] = piece

# Función para verificar si hay un ganador
def check_winner(board, piece):
    # Verificar en horizontal
    for row in range(6):
        for col in range(4):
            if board[row][col] == piece and board[row][col+1] == piece and board[row][col+2] == piece and board[row][col+3] == piece:
                return True

    # Verificar en vertical
    for row in range(3):
        for col in range(7):
            if board[row][col] == piece and board[row+1][col] == piece and board[row+2][col] == piece and board[row+3][col] == piece:
                return True

    # Verificar en diagonal (izquierda a derecha)
    for row in range(3):
        for col in range(4):
            if board[row][col] == piece and board[row+1][col+1] == piece and board[row+2][col+2] == piece and board[row+3][col+3] == piece:
                return True

    # Verificar en diagonal (derecha a izquierda)
    for row in range(3):
        for col in range(3, 7):
            if board[row][col] == piece and board[row+1][col-1] == piece and board[row+2][col-2] == piece and board[row+3][col-3] == piece:
                return True

    return False

# Función para verificar si el tablero está lleno
def is_board_full(board):
    return np.all(board != 0)

# Función para imprimir el tablero
def print_board(board):
    print(np.flip(board, 0))

# Juego automático
current_player = 1

while True:
    # Simular el movimiento del jugador actual
    col = np.random.randint(0, 7)
    available_rows = np.where(board[:, col] == 0)[0]
    if len(available_rows) > 0:
        row = np.max(available_rows)
        drop_piece(board, row, col, current_player)

        # Imprimir el tablero
        print_board(board)
        print()

        # Verificar si hay un ganador
        if check_winner(board, current_player):
            print(f"¡El jugador {current_player} gana!")
            break

        # Verificar si el tablero está lleno
        if is_board_full(board):
            print("¡Empate!")
            break

        # Cambiar al siguiente jugador
        current_player = 2 if current_player == 1 else 1


In [ ]:
import numpy as np

# Crear el tablero
board = np.full((6, 7), "·", dtype=str)

# Función para colocar una ficha en el tablero
def drop_piece(board, row, col, piece):
    board[row][col] = piece

# Función para verificar si hay un ganador
def check_winner(board, piece):
    # Verificar en horizontal
    for row in range(6):
        for col in range(4):
            if board[row][col] == piece and board[row][col+1] == piece and board[row][col+2] == piece and board[row][col+3] == piece:
                return True

    # Verificar en vertical
    for row in range(3):
        for col in range(7):
            if board[row][col] == piece and board[row+1][col] == piece and board[row+2][col] == piece and board[row+3][col] == piece:
                return True

    # Verificar en diagonal (izquierda a derecha)
    for row in range(3):
        for col in range(4):
            if board[row][col] == piece and board[row+1][col+1] == piece and board[row+2][col+2] == piece and board[row+3][col+3] == piece:
                return True

    # Verificar en diagonal (derecha a izquierda)
    for row in range(3):
        for col in range(3, 7):
            if board[row][col] == piece and board[row+1][col-1] == piece and board[row+2][col-2] == piece and board[row+3][col-3] == piece:
                return True

    return False

# Función para verificar si el tablero está lleno
def is_board_full(board):
    return np.all(board != "·")

# Función para imprimir el tablero
def print_board(board):
    print(np.flip(board, 0))

# Juego automático
current_player = "X"

while True:
    # Simular el movimiento del jugador actual
    col = np.random.randint(0, 7)
    available_rows = np.where(board[:, col] == "·")[0]
    if len(available_rows) > 0:
        row = np.max(available_rows)
        drop_piece(board, row, col, current_player)

        # Imprimir el tablero
        print_board(board)
        print()

        # Verificar si hay un ganador
        if check_winner(board, current_player):
            print(f"¡El jugador {current_player} gana!")
            break

        # Verificar si el tablero está lleno
        if is_board_full(board):
            print("¡Empate!")
            break

        # Cambiar al siguiente jugador
        current_player = "O" if current_player == "X" else "X"


In [ ]:
import numpy as np

# Crear el tablero
board = np.full((6, 7), "·", dtype=str)

# Función para colocar una ficha en el tablero
def drop_piece(board, row, col, piece):
    board[row][col] = piece

# Función para verificar si hay un ganador
def check_winner(board, piece):
    # Verificar en horizontal
    for row in range(6):
        for col in range(4):
            if board[row][col] == piece and board[row][col+1] == piece and board[row][col+2] == piece and board[row][col+3] == piece:
                return True

    # Verificar en vertical
    for row in range(3):
        for col in range(7):
            if board[row][col] == piece and board[row+1][col] == piece and board[row+2][col] == piece and board[row+3][col] == piece:
                return True

    # Verificar en diagonal (izquierda a derecha)
    for row in range(3):
        for col in range(4):
            if board[row][col] == piece and board[row+1][col+1] == piece and board[row+2][col+2] == piece and board[row+3][col+3] == piece:
                return True

    # Verificar en diagonal (derecha a izquierda)
    for row in range(3):
        for col in range(3, 7):
            if board[row][col] == piece and board[row+1][col-1] == piece and board[row+2][col-2] == piece and board[row+3][col-3] == piece:
                return True

    return False

# Función para verificar si el tablero está lleno
def is_board_full(board):
    return np.all(board != "·")

# Función para imprimir el tablero
def print_board(board):
    print(np.flip(board, 0))

# Juego automático
current_player = "X"

while True:
    # Simular el movimiento del jugador actual
    col = np.random.randint(0, 7)
    available_rows = np.where(board[:, col] == "·")[0]
    if len(available_rows) > 0:
        row = np.max(available_rows)
        drop_piece(board, row, col, current_player)

        # Imprimir el tablero
        for fila in board:
            print(*fila)
        #print_board(board)
        print()

        # Verificar si hay un ganador
        if check_winner(board, current_player):
            print(f"¡El jugador {current_player} gana!")
            break

        # Verificar si el tablero está lleno
        if is_board_full(board):
            print("¡Empate!")
            break

        # Cambiar al siguiente jugador
        current_player = "O" if current_player == "X" else "X"


In [ ]:
import numpy as np

# Crear el tablero
board = np.full((6, 7), "·", dtype=str)

# Función para colocar una ficha en el tablero
def drop_piece(board, row, col, piece):
    board[row][col] = piece

# Función para obtener la posición más baja disponible en una columna
def get_next_row(board, col):
    for row in range(5, -1, -1):
        if board[row][col] == "·":
            return row
    return -1

# Función para verificar si hay un ganador
def check_winner(board, piece):
    # Verificar en horizontal
    for row in range(6):
        for col in range(4):
            if board[row][col] == piece and board[row][col+1] == piece and board[row][col+2] == piece and board[row][col+3] == piece:
                return True

    # Verificar en vertical
    for row in range(3):
        for col in range(7):
            if board[row][col] == piece and board[row+1][col] == piece and board[row+2][col] == piece and board[row+3][col] == piece:
                return True

    # Verificar en diagonal (izquierda a derecha)
    for row in range(3):
        for col in range(4):
            if board[row][col] == piece and board[row+1][col+1] == piece and board[row+2][col+2] == piece and board[row+3][col+3] == piece:
                return True

    # Verificar en diagonal (derecha a izquierda)
    for row in range(3):
        for col in range(3, 7):
            if board[row][col] == piece and board[row+1][col-1] == piece and board[row+2][col-2] == piece and board[row+3][col-3] == piece:
                return True

    return False

# Función para verificar si el tablero está lleno
def is_board_full(board):
    return np.all(board != "·")

# Función para imprimir el tablero
def print_board(board):
    print(np.flip(board, 0))

# Juego automático
current_player = "X"

while True:
    if current_player == "X":
        # Jugada inteligente del jugador X
        available_cols = np.where(board[0] == "·")[0]
        for col in available_cols:
            temp_board = np.copy(board)
            row = get_next_row(temp_board, col)
            drop_piece(temp_board, row, col, current_player)
            if check_winner(temp_board, current_player):
                drop_piece(board, row, col, current_player)
                break
        else:
            # Si no hay una jugada ganadora, realizar una jugada aleatoria
            col = np.random.choice(available_cols)
            row = get_next_row(board, col)
            drop_piece(board, row, col, current_player)
    else:
        # Jugada aleatoria del jugador O
        col = np.random.choice(np.where(board[0] == "·")[0])
        row = get_next_row(board, col)
        drop_piece(board, row, col, current_player)

    # Imprimir el tablero
    #print_board(board)
    for fila in board:
        print(*fila)
    print()

    # Verificar si hay un ganador
    if check_winner(board, current_player):
        print(f"¡El jugador {current_player} gana!")
        break

    # Verificar si el tablero está lleno
    if is_board_full(board):
        print("¡Empate!")
        break

    # Cambiar al siguiente jugador
    current_player = "O" if current_player == "X" else "X"

## Otra versión diferente


In [ ]:
import numpy as np
import random

# Definimos el tablero
tablero = np.full((6,7), "·")

# Función para imprimir el tablero
def imprimir_tablero(tablero):
    for fila in np.flip(tablero, 0):
        print(*fila)
    print()

# Función para verificar si la jugada es válida
def jugada_valida(tablero, col):
    return tablero[5][col] == "·"

# Función para realizar la jugada
def jugar(tablero, fila, col, pieza):
    tablero[fila][col] = pieza

# Función para verificar si hay un ganador
def ganador(tablero, pieza):
    # Verificar filas horizontales
    for c in range(7-3):
        for r in range(6):
            if tablero[r][c] == pieza and tablero[r][c+1] == pieza and tablero[r][c+2] == pieza and tablero[r][c+3] == pieza:
                return True

    # Verificar columnas verticales
    for c in range(7):
        for r in range(6-3):
            if tablero[r][c] == pieza and tablero[r+1][c] == pieza and tablero[r+2][c] == pieza and tablero[r+3][c] == pieza:
                return True

    # Verificar diagonales positivas
    for c in range(7-3):
        for r in range(6-3):
            if tablero[r][c] == pieza and tablero[r+1][c+1] == pieza and tablero[r+2][c+2] == pieza and tablero[r+3][c+3] == pieza:
                return True

    # Verificar diagonales negativas
    for c in range(7-3):
        for r in range(3, 6):
            if tablero[r][c] == pieza and tablero[r-1][c+1] == pieza and tablero[r-2][c+2] == pieza and tablero[r-3][c+3] == pieza:
                return True

    return False


# Función para obtener la próxima fila disponible en una columna
def proxima_fila_disponible(tablero, col):
    for r in range(6):
        if tablero[r][col] == "·":
            return r

# Función para el jugador X (aleatorio)
def jugador1(tablero):
    columnas_validas = [c for c in range(7) if jugada_valida(tablero, c)]
    if columnas_validas:
        col = random.choice(columnas_validas)
        fila = proxima_fila_disponible(tablero, col)
        jugar(tablero, fila, col, "X")

# Función para el jugador O (aleatorio)
def jugador2(tablero):
    columnas_validas = [c for c in range(7) if jugada_valida(tablero, c)]
    if columnas_validas:
        col = random.choice(columnas_validas)
        fila = proxima_fila_disponible(tablero, col)
        jugar(tablero, fila, col, "O")

# Bucle principal del juego
while True:
    # Verificar si el tablero está lleno
    if not any("·" in row for row in tablero):
        print("¡Empate!")
        break

    # Turno del jugador 1
    jugador1(tablero)
    imprimir_tablero(tablero)
    if ganador(tablero, "X"):
        print("¡Gana el jugador X!")
        break

    # Verificar si el tablero está lleno
    if not any("·" in row for row in tablero):
        print("¡Empate!")
        break

    # Turno del jugador 2
    jugador2(tablero)
    imprimir_tablero(tablero)
    if ganador(tablero, "O"):
        print("¡Gana el jugador O!")
        break


· · · · · · ·
· · · · · · ·
· · · · · · ·
· · · · · · ·
· · · · · · ·
X · · · · · ·

· · · · · · ·
· · · · · · ·
· · · · · · ·
· · · · · · ·
· · · · · · ·
X · · O · · ·

· · · · · · ·
· · · · · · ·
· · · · · · ·
· · · · · · ·
X · · · · · ·
X · · O · · ·

· · · · · · ·
· · · · · · ·
· · · · · · ·
· · · · · · ·
X · · · · · ·
X · · O · · O

· · · · · · ·
· · · · · · ·
· · · · · · ·
· · · · · · ·
X · · · · · ·
X · X O · · O

· · · · · · ·
· · · · · · ·
· · · · · · ·
· · · · · · ·
X · · · · · ·
X · X O · O O

· · · · · · ·
· · · · · · ·
· · · · · · ·
X · · · · · ·
X · · · · · ·
X · X O · O O

· · · · · · ·
· · · · · · ·
· · · · · · ·
X · · · · · ·
X · · · · O ·
X · X O · O O

· · · · · · ·
· · · · · · ·
· · · · · · ·
X · · · · · ·
X · · X · O ·
X · X O · O O

· · · · · · ·
· · · · · · ·
· · · · · · ·
X · · · · · ·
X · · X · O ·
X O X O · O O

· · · · · · ·
· · · · · · ·
· · · · · · ·
X · · X · · ·
X · · X · O ·
X O X O · O O

· · · · · · ·
· · · · · · ·
· · · · · · ·
X · · X · · ·
X · · X ·

# Mi Conecta 4

In [ ]:
import numpy as np
import random
random.seed()

# Definir el tablero
tablero = np.full((6,7), "·")   # filas × columnas = 6 × 7

# Imprimir el tablero
def imprimir_tablero(tablero):
    for fila in np.flip(tablero,0): # invierte las filas, la 1ª es la última
        print(*fila)
    print()


imprimir_tablero(tablero)

· · · · · · ·
· · · · · · ·
· · · · · · ·
· · · · · · ·
· · · · · · ·
· · · · · · ·



In [ ]:
# Create NumPy 2-D array
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

# Use numpy flip() function with 2-d arrays
arr2 = np.flip(arr,0)
print(arr)
print()
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [ ]:
#a = arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
#a = np.arange(1,10).reshape((3,3))
a = np.array([[11, 12, 13, 14, 15, 16, 17],
              [21, 22, 23, 24, 25, 26, 37],
              [31, 32, 33, 34, 35, 36, 47],
              [41, 42, 43, 44, 45, 46, 57],
              [51, 52, 53, 54, 55, 56, 67],
              [61, 62, 63, 64, 65, 66, 77]])
print(a)
print()
print(np.flip(a,0))

[[11 12 13 14 15 16 17]
 [21 22 23 24 25 26 37]
 [31 32 33 34 35 36 47]
 [41 42 43 44 45 46 57]
 [51 52 53 54 55 56 67]
 [61 62 63 64 65 66 77]]

[[61 62 63 64 65 66 77]
 [51 52 53 54 55 56 67]
 [41 42 43 44 45 46 57]
 [31 32 33 34 35 36 47]
 [21 22 23 24 25 26 37]
 [11 12 13 14 15 16 17]]


In [ ]:
# Función para verificar si la jugada es válida
# a esta función se le pasa el tablero completo sin especificar ninguna columna
# la función da True si existe al menos una posición de la fila de index 5
# donde haya un punto medio y por lo tanto se pueda colocar una ficha
def jugada_valida(tablero):
    return np.sum(tablero[5]=="·") > 0

jugada_valida(tablero)

True

In [ ]:
# Función que da las columnas válidas donde poder colocar ficha
def columnas_validas(tablero):
    return [True if tablero[5][col]=="·" else False for col in range(7)]

columnas_validas(tablero)

[True, True, False, True, True, True, True]

In [ ]:
# A simple Connect 4 game in Python

# Define the board size and the number of discs to connect
ROWS = 6
COLS = 7
DISCS = 4

# Define the symbols for the players and the empty spaces
PLAYER1 = "X"
PLAYER2 = "O"
EMPTY = "."

# Create a list of lists to represent the board
board = [[EMPTY for _ in range(COLS)] for _ in range(ROWS)]

# Define a function to print the board
def print_board():
    # Print the column numbers
    print("  ", end="")
    for col in range(COLS):
        print(col + 1, end=" ")
    print()
    # Print the board rows
    for row in range(ROWS):
        print("| ", end="")
        for col in range(COLS):
            print(board[row][col], end=" ")
        print("|")
    # Print the bottom line
    print("-" * (COLS * 2 + 3))

# Define a function to check if a column is valid and not full
def is_valid(col):
    return 0 <= col < COLS and board[0][col] == EMPTY

# Define a function to drop a disc in a column and return the row it lands on
def drop_disc(col, symbol):
    row = ROWS - 1
    while board[row][col] != EMPTY:
        row -= 1
    board[row][col] = symbol
    return row

# Define a function to check if a disc forms a horizontal, vertical or diagonal line of four
def is_winning(row, col, symbol):
    # Check horizontal
    count = 0
    for c in range(COLS):
        if board[row][c] == symbol:
            count += 1
            if count == DISCS:
                return True
        else:
            count = 0
    # Check vertical
    count = 0
    for r in range(ROWS):
        if board[r][col] == symbol:
            count += 1
            if count == DISCS:
                return True
        else:
            count = 0
    # Check positive diagonal
    count = 0
    r = row - min(row, col)
    c = col - min(row, col)
    while r < ROWS and c < COLS:
        if board[r][c] == symbol:
            count += 1
            if count == DISCS:
                return True
        else:
            count = 0
        r += 1
        c += 1
    # Check negative diagonal
    count = 0
    r = row + min(ROWS - row - 1, col)
    c = col - min(ROWS - row - 1, col)
    while r >= 0 and c < COLS:
        if board[r][c] == symbol:
            count += 1
            if count == DISCS:
                return True
        else:
            count = 0
        r -= 1
        c += 1

# Define a function to check if the board is full and the game is a tie
def is_tie():
    return EMPTY not in board[0]

# Define a function to switch the current player's symbol
def switch_player(symbol):
    if symbol == PLAYER1:
        return PLAYER2
    else:
        return PLAYER1

# Start the game loop with player 1's turn
turn = PLAYER1

while True:
    # Print the board and prompt the current player for a column choice
    print_board()
    print(f"It's {turn}'s turn. Choose a column (1-{COLS}): ", end="")

    # Validate the input and drop the disc in the chosen column
    try:
        choice = int(input()) - 1 # Subtract one to match the list index
        if is_valid(choice):
            row = drop_disc(choice, turn)

            # Check if the disc forms a winning line or if the board is full
            if is_winning(row, choice, turn):
                print_board()
                print(f"{turn} wins!")
                break # End the game loop
            elif is_tie():
                print_board()
                print("It's a tie!")
                break # End the game loop

            # Switch to the other player's turn
            turn = switch_player(turn)

        else: # Invalid column choice
            print("Invalid column. Try again.")

    except ValueError: # Invalid input type
        print("Invalid input. Try again.")
